spring:
  application:
    name: hello-spring-cloud-fegin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8765


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#feign自带熔断器默认是关闭的，要手动开启hystrix熔断器
feign:
  hystrix:
    enabled: true
