spring:
  application:
    name: hello-spring-cloud-fegin

server:
  port: 8768


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#feign自带熔断器默认是关闭的，要手动开启hystrix熔断器
feign:
  hystrix:
    enabled: true
